### ISSUE TITLE
Registration of user

### ISSUE THREAD

**Issue by sank8dalvi** [HOD101s/Pay2Mate#1]
My password does qualify the condition specified still it is showing to enter a proper passsword. I tried with password <myname in small case>@123 but this password is not accepted. It shows "Password : at least 1 Special Character 1 Character 1 Digit"

**Comment by HOD101s** [comment]
You need one Character too

**Comment by sank8dalvi** [comment]
As you can see in my password myname are characters, then I used @ which is special character and 123 digits also is present

**Comment by HOD101s** [comment]
Regex has character limit

**Comment by sank8dalvi** [comment]
OK. Now it is working
